In [4]:
import numpy as np


1.	Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

Answer== Vektor'de Np Array'ler 1 boyutlu, Matrix'de birden fazla boyutludurlar veya kullanilirlar.

2.	10 elemanli bir listeden NumPy Array’i olusturunuz.

In [5]:
a = np.array([0,1,2,3,4,5,6,7,8,9,])

print(a)

[0 1 2 3 4 5 6 7 8 9]


3.	Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [7]:
import numpy as np

In [13]:
np.zeros((10,10), dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

4.	Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [14]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.	Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [17]:
np.full((10,10),9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

6.	5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [19]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

7.	-1 ile 1 arasinda 30 adet Array olusturunuz.

In [21]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

8.	0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [22]:
np.random.randint(0,30, (5,6))

array([[ 9,  8, 11,  9,  4, 16],
       [ 8,  5,  7, 23,  6, 17],
       [22,  1, 17, 27, 24, 27],
       [ 4,  8, 26, 29, 24,  7],
       [28, 13, 15,  1, 20, 14]])

9.	Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 

In [23]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10.	0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
a.	eleman sayisini
b.	boyut bilgisini/sayisini
c.	satir X sutun bilgisini
d.	veri tipini numpy metodlariyla yazdiriniz.


In [55]:
a = np.random.randint(0,10, (5,10))
a

array([[6, 1, 1, 7, 7, 7, 4, 5, 8, 2],
       [0, 0, 6, 3, 4, 8, 8, 2, 0, 4],
       [0, 8, 9, 7, 3, 9, 0, 2, 8, 8],
       [6, 8, 7, 2, 0, 8, 9, 4, 2, 7],
       [2, 6, 5, 5, 3, 7, 4, 8, 4, 4]])

In [53]:
a.size

50

In [48]:
a.ndim

2

In [49]:
a.shape

(5, 10)

In [50]:
a.dtype

dtype('int32')

In [51]:
print("Eleman Sayisi=", a.size)
print("Eleman Sayisi=", a.ndim)
print("Eleman Sayisi=", a.shape)
print("Eleman Sayisi=", a.dtype)

Eleman Sayisi= 50
Eleman Sayisi= 2
Eleman Sayisi= (5, 10)
Eleman Sayisi= int32


11.	0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak) 

In [56]:
a = np.random.randint(0,10, (3,4,7))
a

array([[[9, 0, 0, 8, 1, 5, 8],
        [2, 4, 7, 2, 0, 0, 1],
        [0, 7, 2, 0, 2, 0, 8],
        [4, 6, 2, 8, 5, 8, 8]],

       [[0, 2, 4, 5, 3, 7, 2],
        [7, 8, 9, 7, 6, 3, 8],
        [9, 8, 5, 7, 7, 9, 9],
        [4, 7, 1, 2, 9, 4, 9]],

       [[0, 7, 9, 6, 2, 7, 4],
        [6, 3, 6, 7, 1, 1, 9],
        [4, 2, 1, 4, 6, 4, 0],
        [0, 3, 0, 3, 1, 4, 0]]])

12.	Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [85]:
vektor = np.arange(1,15)
vektor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
matris = vektor.reshape(2,7)
matris

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

13.	4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [88]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
a = np.array([10,11,12])

In [99]:
new_array = np.concatenate([a,b,c,d])
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

14.	2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [115]:
a = np.array([[33],
              [23]])

b = np.array([[9,3,7],
              [1,5,6]])

In [116]:
np.hstack([a,b])

array([[33,  9,  3,  7],
       [23,  1,  5,  6]])

15.	Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?  

Axis=0, array'leri satir bazli olusturur.
Azis=1, array'leri sutun bazli olusturur.

16.	Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.

In [127]:
a = np.array([[2,4,6],
            [8,9,10]])
a

array([[ 2,  4,  6],
       [ 8,  9, 10]])

In [128]:
np.concatenate([a,a])

array([[ 2,  4,  6],
       [ 8,  9, 10],
       [ 2,  4,  6],
       [ 8,  9, 10]])

In [129]:
np.concatenate([a,a], axis=1)

array([[ 2,  4,  6,  2,  4,  6],
       [ 8,  9, 10,  8,  9, 10]])

17.	10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [137]:
a = [23,33,44,55,66,77,88,99,79,69]
a

[23, 33, 44, 55, 66, 77, 88, 99, 79, 69]

In [139]:
np.split(a,[3,6,9])

[array([23, 33, 44]), array([55, 66, 77]), array([88, 99, 79]), array([69])]

18.	Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [159]:
a = np.array([55,66,77,38,33,44,88,99,79,69])
a

array([55, 66, 77, 38, 33, 44, 88, 99, 79, 69])

In [160]:
np.sort(a)

array([33, 38, 44, 55, 66, 69, 77, 79, 88, 99])

In [161]:
a,b,c,d = np.split(a,[3,6,9])

In [162]:
a

array([55, 66, 77])

In [163]:
b

array([38, 33, 44])

In [164]:
c

array([88, 99, 79])

In [165]:
d

array([69])

19.	20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [175]:
v = np.random.randint(0,20, size = 20)
v

array([ 8,  5,  2,  5, 16, 15,  9,  0, 16,  7, 11,  3,  9,  4,  9,  2,  3,
        5,  0,  8])

In [179]:
v[3]

5

In [180]:
v[5]

15

In [181]:
v[7]

0

20.	10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.

In [183]:
b = np.random.randint(0,10, size=10)
b

array([7, 3, 7, 6, 8, 6, 0, 7, 1, 5])

In [184]:
b[4] = 33

In [185]:
b

array([ 7,  3,  7,  6, 33,  6,  0,  7,  1,  5])

21.	“Diagonal Matrix” ve “Trace Matrix”  kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

22.	5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [199]:
a = np.eye(5,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

23.	10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [195]:
a = np.arange(10,20)
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

24.	10X10 luk bir matris olusturunuz ve ;
 .	3.satir ve 5.sutuna ulasiniz.
a.	5.sutunun tum satirlarina ulasiniz.
b.	Tum sutunlarin 2.satirlarina ulasiniz.
c.	tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
d.	satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
e.	satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
f.	sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
g.	5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 


In [252]:
mtrx = np.random.randint(0,50, size = (10,10))
mtrx

array([[ 8,  0, 36, 47, 32, 12, 45, 25, 14, 43],
       [39,  3, 21, 33, 15, 26, 47, 28, 17, 36],
       [ 2, 10, 45, 11, 23, 17, 25, 49, 47, 12],
       [ 9, 38,  9, 27, 29, 47,  6, 13, 26, 15],
       [36,  3, 13, 23, 40, 20, 20, 20, 35, 48],
       [15, 14, 48,  5, 43, 23, 40, 30, 33, 23],
       [ 7, 31, 31,  3, 17, 39, 40, 14, 37, 33],
       [29, 18, 49, 24, 40, 11, 12, 30,  9, 21],
       [28, 19,  6, 12, 21,  8, 17, 14,  6, 48],
       [14, 16, 19, 46,  3,  1, 13, 25, 30, 16]])

In [253]:
# 3.satir ve 5.sutuna ulasiniz.
mtrx [2,4]

23

In [254]:
# 5.sutunun tum satirlarina ulasiniz.
mtrx[: , 4]

array([32, 15, 23, 29, 40, 43, 17, 40, 21,  3])

In [255]:
# Tum sutunlarin 2.satirlarina ulasiniz.
mtrx[1, :]

array([39,  3, 21, 33, 15, 26, 47, 28, 17, 36])

In [257]:
# Tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
mtrx [2:8, : ]

array([[ 2, 10, 45, 11, 23, 17, 25, 49, 47, 12],
       [ 9, 38,  9, 27, 29, 47,  6, 13, 26, 15],
       [36,  3, 13, 23, 40, 20, 20, 20, 35, 48],
       [15, 14, 48,  5, 43, 23, 40, 30, 33, 23],
       [ 7, 31, 31,  3, 17, 39, 40, 14, 37, 33],
       [29, 18, 49, 24, 40, 11, 12, 30,  9, 21]])

In [258]:
# Tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
mtrx [1:8,:]

array([[39,  3, 21, 33, 15, 26, 47, 28, 17, 36],
       [ 2, 10, 45, 11, 23, 17, 25, 49, 47, 12],
       [ 9, 38,  9, 27, 29, 47,  6, 13, 26, 15],
       [36,  3, 13, 23, 40, 20, 20, 20, 35, 48],
       [15, 14, 48,  5, 43, 23, 40, 30, 33, 23],
       [ 7, 31, 31,  3, 17, 39, 40, 14, 37, 33],
       [29, 18, 49, 24, 40, 11, 12, 30,  9, 21]])

In [259]:
# Satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
mtrx [2:5, 3:7]

array([[11, 23, 17, 25],
       [27, 29, 47,  6],
       [23, 40, 20, 20]])

In [260]:
# Satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
mtrx [5:,:4]

array([[15, 14, 48,  5],
       [ 7, 31, 31,  3],
       [29, 18, 49, 24],
       [28, 19,  6, 12],
       [14, 16, 19, 46]])

In [262]:
# Sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
mtrx [:, [3,6,9]]

array([[47, 45, 43],
       [33, 47, 36],
       [11, 25, 12],
       [27,  6, 15],
       [23, 20, 48],
       [ 5, 40, 23],
       [ 3, 40, 33],
       [24, 12, 21],
       [12, 17, 48],
       [46, 13, 16]])

In [264]:
# 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 
mtrx [5,5]=1986
mtrx

array([[   8,    0,   36,   47,   32,   12,   45,   25,   14,   43],
       [  39,    3,   21,   33,   15,   26,   47,   28,   17,   36],
       [   2,   10,   45,   11,   23,   17,   25,   49,   47,   12],
       [   9,   38,    9,   27,   29,   47,    6,   13,   26,   15],
       [  36,    3,   13,   23,   40,   20,   20,   20,   35,   48],
       [  15,   14,   48,    5,   43, 1986,   40,   30,   33,   23],
       [   7,   31,   31,    3,   17,   39,   40,   14,   37,   33],
       [  29,   18,   49,   24,   40,   11,   12,   30,    9,   21],
       [  28,   19,    6,   12,   21,    8,   17,   14,    6,   48],
       [  14,   16,   19,   46,    3,    1,   13,   25,   30,   16]])

25.	0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
 .	20 den buyuk olan kac deger var.
a.	30’dan kucuk kac deger var
b.	icerisinde 33 gecen kac deger var
c.	olusturulan arrayin tum elemanlarini 5 ile carpin.
d.	olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.


In [275]:
a =np.arange(0,50,5)
a,20

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45]), 20)

In [278]:
# 20 den buyuk olan kac deger var.
sum(a>20)

5

In [279]:
# 30'dan kucuk kac deger var
sum(a<30)

6

In [280]:
# icerisinde 33 gecen kac deger var
sum(a == 33)

0

In [281]:
# olusturulan arrayin tum elemanlarini 5 ile carpin.
a*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [282]:
# olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

26.	0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
 .	orlamasini aliniz.
a.	standart sapmasini aliniz.
b.	varyansini aliniz.
c.	median’ini aliniz.
d.	en kucuk degeri bulunuz.
e.	en buyuk degeri bulunuz.


In [286]:
# 0 ile 1 arasinda 50 elamanli bir array olusturunuz 
a = np.random.normal(0, 1, 50 )
a

array([-0.49007872, -2.31192701,  0.21534701, -1.15166846,  0.00386303,
       -0.71137754, -0.72905313,  0.02803285, -0.49199313,  1.21969451,
        0.67646473, -0.07330258, -0.48066563,  0.13709059,  0.20504958,
       -0.46124209,  1.71152575, -0.76148009,  0.06816076,  0.36566098,
        0.14712098,  0.92674361,  1.7276349 , -0.07313721,  0.43087789,
       -0.11374217,  1.38216522,  1.3807155 , -0.86024202, -0.56864647,
        0.64718106, -0.8388975 ,  2.20818447, -0.43920152,  1.27317965,
       -0.58896953,  0.45555661,  0.37245342, -0.82837652,  1.42192724,
       -1.61688089, -0.53847837, -1.1502891 ,  1.99664587, -0.24596748,
        0.64164799,  2.02712398,  0.70322428, -0.24373781,  0.22886212])

In [287]:
# orlamasini aliniz.
np.mean(a)

0.136655591355525

In [289]:
# standart sapmasini aliniz.
np.std(a)

0.9692494604729865

In [290]:
# varyansini aliniz.
np.var(a)

0.9394445166271754

In [291]:
# median’ini aliniz.
np.median(a)

0.04809680479331284

In [292]:
#en kucuk degeri bulunuz.
np.min(a)

-2.311927014657625

In [293]:
#en buyuk degeri bulunuz.
np.max(a)

2.208184466917157


Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. Matris uretme islemini np.random.random((axb)) fonksiyonu ile yapabilirsiniz.(size kalmis) 1:30 Cuma aksamina kadar odevlerin hepsini gondermenizi rica ediyorum. Ayrica, matris odevinin ekran goruntusunu yada ekran videosunu gruba atmanizi istiyorum. Deneme matrislerini de gonderebilirsiniz. Hepinize kolay gelsin.